<template><section class="shared-completion" aria-label="家庭库存完成核对"><h3>完成烹饪 · 家庭库存实际使用</h3><p>逐批次填写实际使用量，沿用库存单位，不自动转换为克或份。</p><p v-if="error" role="alert">{{ error }}</p><p v-if="receipt" role="status">家庭库存扣减已回读确认，本会话不会重复扣减。</p><p v-if="pending">上次响应未确认，请保留原凭证核对。</p><button :disabled="busy" @click="load">重新读取家庭库存与凭证</button><template v-if="!receipt"><label v-for="r in items" :key="r.id"><input type="checkbox" :value="r.id" v-model="selected" :disabled="busy||!!pending">{{ r.name }} · {{ r.quantity }} {{ r.unit }} · {{ r.freshness?.freshness_label||'鲜度未知' }}<input type="number" min="0.000001" :max="r.quantity" step="any" v-model="r.used" :aria-label="r.name+'实际使用量'" :disabled="busy||!!pending"></label><button :disabled="busy||!!pending||!selected.length" @click="submit">确认完成并扣减家庭批次</button></template><button v-if="pending" :disabled="busy" @click="retry">使用原凭证核对并重试</button><button :disabled="busy" @click="finishOnly">{{ session.status==='completed'?'关闭核对':'仅记录完成，不扣库存' }}</button><button v-if="session.status!=='completed'" :disabled="busy" @click="$emit('close')">继续烹饪</button></section></template>
<script setup>
import {ref,onMounted,onBeforeUnmount} from 'vue'
import {businessApi,apiError} from '../api/business'
import {completionSync} from '../api/completions'
import {usePendingCommand} from '../services/businessCommands'
import {readUserId} from '../services/recognitionDraft'
const props=defineProps({session:Object,engine:Object}),emit=defineEmits(['changed','close']),family=props.session.recipe.inventory_scope.family_id,items=ref([]),selected=ref([]),receipt=ref(null)
let active=true,revision=0;const valid=()=>active&&readUserId()===props.session.user
const {busy,error,pending,send,retry}=usePendingCommand('family-consume:'+family,async()=>{await load();window.dispatchEvent(new CustomEvent('cookx:inventory-changed',{detail:{user:props.session.user}}))})
async function load(){const version=++revision;try{const data=await businessApi('/households/'+family);let proof=null;try{proof=(await businessApi('/households/'+family+'/consumption/'+props.session.id)).receipt}catch(e){if(e.response?.status!==404)throw e}if(!valid()||version!==revision)return;items.value=data.inventory.map(r=>({...r,used:''}));selected.value=[];receipt.value=proof;if(proof){props.engine.state.consumption='confirmed';props.engine.persist();emit('changed')}}catch(e){if(valid()&&version===revision)error.value=apiError(e)}}
function complete(){if(props.engine.state.status!=='completed')props.engine.finish();try{completionSync.enqueue(props.engine.state);completionSync.sync(props.session.user).catch(()=>{})}catch(e){error.value='本地完成已保留，成长同步待核对：'+e.message}emit('changed')}
function finishOnly(){if(!valid()||busy.value)return;complete();emit('close')}
async function submit(){if(!valid()||busy.value||pending.value||receipt.value)return;const chosen=items.value.filter(r=>selected.value.includes(r.id));if(!chosen.length||chosen.some(r=>!Number.isFinite(Number(r.used))||Number(r.used)<=0||Number(r.used)>r.quantity)){error.value='请核对实际使用量';return}complete();await send('/households/'+family+'/consumption','post',{session_id:props.session.id,items:chosen.map(r=>({item_id:r.id,expected_version:r.version,quantity:Number(r.used)}))})}
onMounted(load);onBeforeUnmount(()=>{active=false;revision++})
</script>
<style scoped>.shared-completion{margin:0;padding:16px;border:1px solid var(--ck-glass-border);border-radius:var(--ck-radius-lg);background:var(--ck-glass);color:var(--ck-text-2);line-height:1.7;-webkit-backdrop-filter:var(--ck-blur);backdrop-filter:var(--ck-blur)}.shared-completion h3{color:var(--ck-text);font-size:17px}.shared-completion label{display:block;margin:10px 0;padding:12px;border-radius:14px;background:var(--ck-fill);color:var(--ck-text)}.shared-completion input[type=checkbox]{width:20px;height:20px;margin-right:8px;vertical-align:-4px;accent-color:var(--ck-heat-deep)}.shared-completion button{border:1px solid var(--ck-glass-border);border-radius:999px;background:var(--ck-fill-strong);color:var(--ck-text);font:inherit;font-size:13px;font-weight:600;min-height:38px;padding:0 14px;margin:4px 6px 4px 0}.shared-completion input[type=number]{box-sizing:border-box;min-height:42px;padding:0 12px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:rgba(255,255,255,.07);color:var(--ck-text);font:inherit;display:block;width:120px;margin-top:8px}</style>
