import test from 'node:test'
import assert from 'node:assert/strict'
import {consumptionPreview,createConsumption,consumptionKey} from './inventoryConsumption.js'
function setup(mode='success'){let rows=[{id:'1',name:'番茄',quantity:2}],writes=0;const saved=new Map();const storage={getItem:k=>saved.get(k),setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)};const api=createConsumption({storage,read:async()=>structuredClone(rows),write:async()=>{writes++;if(mode==='business')return {status:'error'};rows[0].quantity--;if(mode==='lost')throw Error('network');return {status:'success'}}});return {api,storage,items:consumptionPreview(rows),writes:()=>writes}}
test('aliases and duplicate batches prohibit automatic consumption',()=>{const result=consumptionPreview([{id:'1',name:'tomato',quantity:2},{id:'2',name:'西红柿',quantity:3}]);assert.ok(result.every(r=>r.blocked));assert.ok(consumptionPreview([{id:'1',name:'盐',quantity:0.5}])[0].blocked)})
test('successful write must read back and cannot run twice for one session',async()=>{const f=setup();assert.equal((await f.api.submit('u','s',f.items))[0].quantity,1);await assert.rejects(()=>f.api.submit('u','s',f.items));assert.equal(f.writes(),1)})
test('lost acknowledgement survives reload and only reconciles without writing again',async()=>{const f=setup('lost');await assert.rejects(()=>f.api.submit('u','s',f.items));assert.equal(f.api.pending('u').status,'uncertain');await assert.rejects(()=>f.api.submit('u','s',f.items));await f.api.reconcile('u');assert.equal(f.writes(),1);assert.equal(f.api.pending('u').status,'confirmed')})
test('business failure and duplicate clicks',async()=>{const f=setup('business');const pending=f.api.submit('u','s',f.items);await assert.rejects(()=>f.api.submit('u','s',f.items));await assert.rejects(()=>pending);assert.equal(f.api.pending('u'),null);assert.equal(f.writes(),1)})
test('corrupt ledger and stale inventory block submission before write',async()=>{const f=setup();await assert.rejects(()=>f.api.submit('u','s',[{...f.items[0],quantity:9}]));assert.equal(f.writes(),0);f.storage.setItem(consumptionKey('u'),'{bad');await assert.rejects(()=>f.api.submit('u','s',f.items));assert.equal(f.writes(),0)})
