const {chromium}=require(process.env.COOKX_PLAYWRIGHT||'playwright')
const assert=require('node:assert/strict'),fs=require('node:fs')
;(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.COOKX_CHROME?{executablePath:process.env.COOKX_CHROME}:{})})
 try {
  const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[]
  fs.mkdirSync('tmp/copilot',{recursive:true})
  page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message))
  await page.addInitScript(()=>{localStorage.setItem('user',JSON.stringify({id:'copilot-test'}));window.SpeechRecognition=undefined;window.webkitSpeechRecognition=undefined})
  let mode='bad',consumeCalls=0
  let inventory=[{id:'milk',name:'牛奶',quantity:2},{id:'t1',name:'番茄',quantity:2},{id:'t2',name:'tomato',quantity:3}]
  await page.route('**/api/**',async route=>{
   const url=route.request().url()
   if(url.includes('recommend-recipe'))return route.fulfill({json:{status:'success',recipe:mode==='bad'?'{invalid':{dish_name:'测试菜谱',steps:['准备食材',{text:'热锅',time_estimate:60},{text:'放入食材',time_estimate:90}],used_ingredients:[],missing:['盐']}}})
   if(url.includes('inventory/freshness'))return route.fulfill({json:{items:[],evaluated_at:new Date().toISOString()}})
   if(url.includes('consume-ingredients')){consumeCalls++;inventory[0].quantity--;return route.fulfill({json:{status:'success'}})}
   if(url.includes('/inventory'))return route.fulfill({json:inventory})
   if(url.includes('/tts'))return route.fulfill({status:503,json:{detail:'test speech unavailable'}})
   return route.fulfill({json:[]})
  })
  await page.goto((process.env.COOKX_BASE_URL||'http://127.0.0.1:4173')+'/#/home?tab=AiChef')
  const input=page.getByPlaceholder('告诉 CookX 你想做什么…')
  await input.fill('测试菜谱');await input.press('Enter')
  await page.getByText('菜谱 JSON 无法解析，请重新生成',{exact:true}).waitFor()
  assert.equal(await input.inputValue(),'测试菜谱')
  mode='valid';await page.getByRole('button',{name:'重新生成菜谱',exact:true}).click()
  await page.getByRole('button',{name:'开始指导',exact:true}).click()
  await page.getByText('时长未提供',{exact:true}).waitFor()
  await page.getByRole('button',{name:'下一步',exact:true}).click()
  await page.getByText('热锅',{exact:true}).first().waitFor()
  await page.waitForFunction(()=>document.querySelector('.current-step-card .panel-heading')?.innerText.includes('00:59'))
  const deadline=await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).timers[1].deadline)
  await page.getByRole('button',{name:'重新播报',exact:true}).click()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).timers[1].deadline),deadline)
  await page.reload();await page.getByRole('button',{name:'恢复烹饪',exact:true}).click()
  await page.getByText('热锅',{exact:true}).first().waitFor()
  await page.getByRole('button',{name:'暂停计时',exact:true}).click()
  const paused=await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).timers[1])
  assert.equal(paused.deadline,null)
  await page.getByRole('button',{name:'上一步',exact:true}).click()
  await page.getByRole('button',{name:'下一步',exact:true}).click()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).timers[1].remainingMs),paused.remainingMs)
  await page.getByRole('button',{name:'点击说一句指令',exact:true}).click()
  await page.getByText('此设备没有可用语音识别，请使用文字指令或按钮',{exact:true}).waitFor()
  await page.evaluate(()=>{window.SpeechRecognition=class {start(){window.testRecognizer=this}abort(){}}})
  await page.getByRole('button',{name:'点击说一句指令',exact:true}).click()
  await page.waitForFunction(()=>window.testRecognizer?.onresult)
  await page.evaluate(()=>{const result=[{transcript:'继续计时',confidence:0.5}];result.isFinal=true;window.testRecognizer.onresult({results:[result]})})
  await page.getByText('识别结果需要确认，尚未执行',{exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).timers[1].deadline),null)
  await page.locator('.voice-commands').screenshot({path:'tmp/copilot/voice-confirmation.png'})
  await page.locator('.voice-commands').getByRole('button',{name:'继续计时',exact:true}).click()
  assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).timers[1].deadline))
  await page.getByRole('button',{name:'点击说一句指令',exact:true}).click()
  await page.waitForFunction(()=>window.testRecognizer?.onresult)
  await page.evaluate(()=>{const result=[{transcript:'上一步',confidence:0.95}];result.isFinal=true;const cb=window.testRecognizer.onresult;cb({results:[result]});cb({results:[result]})})
  await page.getByText('准备食材',{exact:true}).first().waitFor()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).stepIndex),0)
  await page.getByRole('button',{name:'过咸',exact:true}).click()
  await page.getByRole('button',{name:'取消预览',exact:true}).click()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).recipeVersion),1)
  await page.getByRole('button',{name:'过咸',exact:true}).click()
  await page.locator('.adjustments').screenshot({path:'tmp/copilot/adjustment-preview.png'})
  await page.getByRole('button',{name:'确认调整',exact:true}).click()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).recipeVersion),2)
  await page.getByRole('button',{name:'撤销过咸',exact:true}).click()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).recipeVersion),3)
  await page.locator('.timer-controls input').fill('1')
  await page.getByRole('button',{name:'开始计时',exact:true}).click()
  await page.getByText('第 1 步计时结束，请检查烹饪状态；不会自动跳步。',{exact:true}).waitFor()
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).stepIndex),0)
  await page.getByRole('button',{name:'下一步',exact:true}).click()
  await page.getByRole('button',{name:'下一步',exact:true}).click()
  await page.getByRole('button',{name:'完成烹饪',exact:true}).click()
  await page.getByRole('heading',{name:'完成烹饪 · 实际使用清单'}).waitFor()
  await page.locator('.completion label').filter({hasText:'牛奶'}).getByRole('checkbox').check()
  assert.equal(await page.locator('.completion label').filter({hasText:'番茄'}).getByRole('checkbox').isDisabled(),true)
  assert.equal(consumeCalls,0)
  await page.locator('.completion').screenshot({path:'tmp/copilot/completion-review.png'})
  await page.getByRole('button',{name:'确认完成并扣减所选',exact:true}).click()
  await page.getByText('库存扣减已回读确认。',{exact:true}).waitFor()
  assert.equal(consumeCalls,1)
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('cookx:cooking:v1:copilot-test')).status),'completed')
  await page.locator('.device-diagnostics summary').click()
  await page.getByRole('button',{name:'重新核对设备状态',exact:true}).click()
  await page.getByText('浏览器不支持 Bluetooth Classic，请使用 Android 安装包。',{exact:true}).waitFor()
  const downloadPromise=page.waitForEvent('download')
  await page.getByRole('button',{name:'导出设备诊断',exact:true}).click()
  const download=await downloadPromise
  const log=JSON.parse(fs.readFileSync(await download.path(),'utf8'))
  assert.equal(log.source,'browser-no-hardware');assert.deepEqual(log.records,[])
  fs.mkdirSync('tmp/copilot' ,{recursive:true});await page.screenshot({path:'tmp/copilot/cooking-mobile.png',fullPage:true})
  assert.deepEqual(errors,[])
  console.log(JSON.stringify({suite:'copilot',checks:['invalid-json','retained-input','retry','unknown-duration','timer-independent-of-speech','reload-restore','paused-step-return','asr-unavailable','low-confidence-confirmation','duplicate-final-result','adjustment-preview-cancel-apply-undo','timer-expiry-no-skip','batch-protection','completion-consumption-readback','diagnostics-export'],errors}))
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)})
