package com.smartcooking.app.offline
import com.smartcooking.app.core.*
import kotlinx.serialization.json.*
import org.junit.Assert.*
import org.junit.Test
import java.io.File

class LocalEngineTest {
    private val recipes=AppJson.parseToJsonElement(File("src/main/assets/offline/recipes.json").readText()).asArray()!!.mapNotNull{it.asObject()}
    private var disk:String?=null
    private val engine=LocalEngine(recipes,null,{disk=it})
    private val auth=mapOf("Authorization" to "Bearer ${engine.initialSession().str("access_token")}")
    private fun call(m:String,p:String,b:JsonElement=EmptyObject,q:Map<String,String> = emptyMap(),h:Map<String,String> = auth):JsonObject {
        val r=engine.request(m,"/api$p",b,q,h);assertEquals("$m $p ${r.body}",200,r.code);return r.body.asObject()?:EmptyObject
    }
    private fun rows(p:String)=call("GET",p).objects("items")
    @Test fun richSeedAndPersistence() {assertEquals(32,engine.stock("lin").size);assertTrue(recipes.size>=27);val restored=LocalEngine(recipes,disk,{disk=it});assertEquals(engine.db,restored.db);assertEquals(6,rows("/v3/community/posts").size)}
    @Test fun unauthorizedAndCrossAccountAreRejected(){assertEquals(401,engine.request("GET","/api/inventory").code);assertEquals(403,engine.request("GET","/api/inventory",query=mapOf("user_id" to "chen"),headers=auth).code)}
    @Test fun editNullFieldsPersistAndStaleWriteFails(){val r=engine.stock("lin").first();val h=auth+mapOf("If-Match" to r.str("_revision")!!);call("PUT","/inventory/${r.str("id")}",jsonOf("shelf_life" to 3.5,"purchase_time" to null),h=h);val edited=engine.find("stock",r.str("id")!!);assertEquals(3.5,edited.num("shelf_life")!!,0.0);assertNull(edited.str("purchase_time"));assertEquals(409,engine.request("PUT","/api/inventory/${r.str("id")}",jsonOf("quantity" to 9),headers=h).code)}
    @Test fun addRecognitionIsIdempotent(){val b=jsonOf("user_id" to "lin","confirmed" to true,"items" to listOf(jsonOf("name" to "葡萄","quantity" to 3)));val h=auth+mapOf("Idempotency-Key" to "recognition-1");repeat(2){call("POST","/inventory/confirm-recognition",b,h=h)};assertEquals(1,engine.stock("lin").count{it.str("name")=="葡萄"})}
    @Test fun deductionAndReceiptSurviveRestart(){val r=engine.stock("lin").first();val b=jsonOf("user_id" to "lin","idempotency_key" to "consume-1","items" to listOf(jsonOf("item_id" to r.str("id"),"quantity" to 1,"expected_quantity" to r.num("quantity"),"expected_revision" to r.str("_revision"))));repeat(2){call("POST","/inventory/consume",b)};assertEquals(r.num("quantity")!!-1,engine.find("stock",r.str("id")!!).num("quantity")!!,0.0);assertEquals("consume-1",call("GET","/inventory/consumption/consume-1").str("idempotency_key"));val restored=LocalEngine(recipes,disk,{disk=it});assertEquals(200,restored.request("POST","/api/inventory/consume",b,headers=auth).code)}
    @Test fun failedMultiBatchDeductionRollsBack(){val r=engine.stock("lin").first();val old=engine.db;val b=jsonOf("idempotency_key" to "bad","items" to listOf(jsonOf("item_id" to r.str("id"),"quantity" to 1,"expected_quantity" to r.num("quantity"),"expected_revision" to r.str("_revision")),jsonOf("item_id" to "missing","quantity" to 1)));assertEquals(404,engine.request("POST","/api/inventory/consume",b,headers=auth).code);assertEquals(old,engine.db)}
    @Test fun storageFailureRollsBack(){var reject=false;val e=LocalEngine(recipes,null,{if(reject)error("full")});val h=mapOf("Authorization" to "Bearer ${e.initialSession().str("access_token")}");val old=e.db;reject=true;assertEquals(500,e.request("POST","/api/add-to-inventory",JsonArray(listOf(jsonOf("name" to "测试食材","quantity" to 1))),headers=h).code);assertEquals(old,e.db)}
    @Test fun logoutRevokesAccess(){call("POST","/auth/logout");assertEquals(401,engine.request("GET","/api/inventory",headers=auth).code)}
    @Test fun accountSwitchDoesNotShareStock(){val login=call("POST","/login",jsonOf("username" to "chen","password" to "cookx123"));val h=mapOf("Authorization" to "Bearer ${login.str("access_token")}");val r=engine.request("GET","/api/inventory",headers=h);assertEquals(3,r.body.asArray()!!.size);assertEquals(403,engine.request("GET","/api/user/lin",headers=h).code)}
    @Test fun fullShoppingClaimPurchaseStockIn(){val r=rows("/v3/households/home/shopping").first{it.str("id")=="shop-2"};val root="/v3/households/home/shopping/shop-2";call("POST","$root/state",jsonOf("action" to "claim","expected_version" to r.num("version")));assertEquals(409,engine.request("POST","/api$root/state",jsonOf("action" to "claim","expected_version" to 1),headers=auth).code);call("POST","$root/state",jsonOf("action" to "bought","expected_version" to 2));val before=engine.stock("home").size;val b=jsonOf("idempotency_key" to "stockin","expected_version" to 3,"name" to "牛奶","quantity" to 1000,"unit" to "毫升","storage_type" to "冷藏");repeat(2){call("POST","$root/stock-in",b)};assertEquals(before+1,engine.stock("home").size);assertEquals("stocked",engine.find("shopping","shop-2").str("state"))}
    @Test fun familyTransferPreservesDates(){val r=engine.stock("lin").first();call("POST","/v3/households/home/transfer",jsonOf("item_id" to r.str("id"),"expected_inventory_version" to engine.stockVersion("lin"),"confirmed" to true));assertFalse(engine.stock("lin").contains(r));assertEquals(r.str("expiry_date"),engine.find("stock",r.str("id")!!).str("expiry_date"))}
    @Test fun removedMemberLosesAccess(){call("DELETE","/v3/households/home/members/chen",jsonOf("expected_version" to 1));val login=call("POST","/login",jsonOf("username" to "chen","password" to "cookx123"));assertEquals(403,engine.request("GET","/api/v3/households/home",headers=mapOf("Authorization" to "Bearer ${login.str("access_token")}")).code)}
    @Test fun recipeCopyFavoriteAndCheck(){val source=jsonOf("source_type" to "standard","source_id" to "recipe_001","expected_source_version" to "1");val copy=call("POST","/v3/recipes/copies",source).obj("copy")!!;assertEquals("番茄炒鸡蛋",copy.obj("recipe")!!.str("dish_name"));assertTrue(call("GET","/v3/recipes/copies/${copy.str("id")}/check").objects("ingredients").isNotEmpty());val fav=call("POST","/v3/recipes/favorites",source).obj("favorite")!!;call("DELETE","/v3/recipes/favorites/${fav.str("id")}",jsonOf("expected_version" to 1))}
    @Test fun communityLikeCommentHideAndDelete(){val post=call("POST","/v3/community/posts",jsonOf("text" to "今天的一餐","confirmed" to true,"recipe_copy_id" to "copy-0")).obj("post")!!;val root="/v3/community/posts/${post.str("id")}";val vote=jsonOf("liked" to true,"expected_version" to 0,"idempotency_key" to "vote");repeat(2){call("PUT","$root/likes",vote)};assertEquals(1.0,call("GET","$root/likes").num("count")!!,0.0);call("POST","$root/comments",jsonOf("text" to "完成啦"));assertEquals(1,rows("$root/comments").size);call("POST","$root/moderation",jsonOf("expected_version" to 1,"hidden" to true,"reason" to "调整内容"));assertFalse(rows("/v3/community/hot").any{it.str("id")==post.str("id")});call("DELETE",root,jsonOf("expected_version" to 2))}
    @Test fun growthCompletionIsDeduplicatedAndBadgesAvailable(){val b=jsonOf("session_id" to "new-session","confirmed" to true,"recipe" to recipes[0],"recipe_version" to 1,"completed_at" to engine.now());repeat(2){call("POST","/v3/growth/completions",b)};assertEquals(9.0,call("GET","/v3/growth").num("confirmed_count")!!,0.0);assertTrue(rows("/v3/badges").any{it.obj("award")!=null});call("POST","/v3/challenges/first/join");assertNotNull(rows("/v3/challenges").first().obj("participation"))}
    @Test fun cookedFoodAbnormalSuppressesIdeas(){call("POST","/v3/leftovers/left-rice/events",jsonOf("type" to "abnormal","expected_version" to 1));val ideas=call("GET","/v3/leftovers/left-rice/ideas");assertFalse(ideas.obj("assessment")!!.bool("eligible"));assertTrue(ideas.objects("ideas").isEmpty())}
    @Test fun learningSettingsFeedbackReset(){call("PUT","/v3/learning/settings",jsonOf("enabled" to true,"expected_version" to 0));call("PUT","/v3/learning/feedback/recipe_001",jsonOf("liked" to true,"expected_version" to 1));call("POST","/v3/learning/train");assertNotNull(call("GET","/v3/learning").obj("model"));call("POST","/v3/learning/reset",jsonOf("action" to "clear_feedback"));assertTrue(call("GET","/v3/learning").objects("feedback").isEmpty())}
    @Test fun weeklyMenuSaveCheckAndClone(){val cfg=jsonOf("people" to 2,"max_repeat" to 3,"meals" to (0..6).flatMap{d->listOf("lunch","dinner").map{jsonOf("day" to d,"meal" to it)}},"max_minutes" to 120,"max_difficulty" to 2,"confirm_estimates" to true);val preview=call("POST","/v3/planning/preview",cfg).obj("preview")!!;assertEquals(14,preview.obj("result")!!.objects("meals").size);val menu=call("POST","/v3/planning/menus",jsonOf("preview_id" to preview.str("id"),"expected_version" to 1,"name" to "一周安排")).obj("menu")!!;assertNotNull(call("GET","/v3/planning/menus/${menu.str("id")}/check").obj("menu"));assertNotNull(call("POST","/v3/recipes/copies",jsonOf("source_type" to "menu","source_id" to "${menu.str("id")}|0|lunch|main","expected_source_version" to "1")).obj("copy"))}
    @Test fun menuDoesNotIgnoreUnknownBudgetOrNutrition(){val cfg=jsonOf("meals" to listOf(jsonOf("day" to 0,"meal" to "lunch")),"budget" to 10,"nutrition" to jsonOf("kcal" to jsonOf("min" to 400)));val result=call("POST","/v3/planning/preview",cfg).obj("preview")!!.obj("result")!!;assertEquals("UNKNOWN",result.str("solver_status"));assertTrue(result.objects("meals").isEmpty());assertTrue(result.strings("issues").size>=2)}
    @Test fun preferencesAndProfileRoundTrip(){call("PUT","/v3/preferences",jsonOf("expected_version" to 0,"values" to jsonOf("taste" to "清淡")));assertEquals("清淡",call("GET","/v3/preferences").obj("preferences")!!.obj("values")!!.str("taste"));val response=call("PUT","/user/lin",q=mapOf("nickname" to "小厨"));assertEquals("小厨",response.obj("user")!!.str("nickname"))}
    @Test fun temperatureHasNoGeneratedEndpoint(){assertEquals(404,engine.request("GET","/api/temperature",headers=auth).code)}
    private fun canonical(v:JsonElement?):JsonElement? = when(v) {
        is JsonObject -> JsonObject(v.mapValues{canonical(it.value)!!})
        is JsonArray -> JsonArray(v.map{canonical(it)!!})
        is JsonPrimitive -> if(!v.isString && v.doubleOrNull!=null) v.double.toJsonElement() else v
        else -> v
    }
    @Test fun freshnessMatchesFormalTimeStorageContract() {
        val rules=AppJson.parseToJsonElement(File("src/main/assets/offline/storage-rules.json").readText()).asObject()!!
        val cases=AppJson.parseToJsonElement(File("src/test/resources/freshness-contract.json").readText()).asArray()!!
        for(value in cases){val c=value.asObject()!!;val actual=localFreshness(c.obj("item")!!,rules,java.time.Instant.parse("2026-09-27T00:00:00Z").toEpochMilli());val expected=c.obj("expected")!!
            for(key in listOf("fresh_score","component_scores","effective_weights","confidence_score","expired","critical","expiring_soon"))assertEquals("$key ${c.obj("item")}",canonical(expected[key]),canonical(actual[key]))}
    }
    @Test fun dislikedIngredientsAndExpiredBatchesNeverReenterRecommendations() {
        val row=engine.stock("lin").first{it.str("name")=="番茄"};engine.replace("stock",row.with("expiry_date" to "2020-01-01T00:00:00Z","purchase_time" to "2019-01-01T00:00:00Z"))
        val output=call("POST","/recommendations",jsonOf("top_k" to 100,"preferences" to jsonOf("disliked_ingredients" to listOf("土豆"))))
        val ids=output.objects("recommendations").map{it.str("recipe_id")};assertFalse("recipe_001" in ids);assertFalse("recipe_002" in ids)
    }
}
