<template><main class="business-page"><header><button @click="router.push('/home')" aria-label="返回首页">‹</button><h1>偏好学习</h1></header><p class="note">主动开启后，只用你明确选择的喜欢与不喜欢学习菜谱标签。在原本合格的候选内调整顺序，不突破忌口、食材风险或菜单硬约束。</p><p v-if="error" role="alert" class="error">{{ error }}</p><section v-if="pending"><p>上次操作结果待确认。</p><button :disabled="busy" @click="retry">核对原操作</button></section><section v-if="data"><h2>{{ data.settings.enabled?'已开启偏好学习':'偏好学习已关闭' }}</h2><p>{{ data.note }}</p><button class="primary" :disabled="busy||!!pending" @click="toggle">{{ data.settings.enabled?'关闭学习，恢复原排序':'我愿意开启偏好学习' }}</button><p>明确反馈 {{ data.feedback.length }} 道菜；独立行为记录 {{ data.activity_count }} 条。</p><button :disabled="busy||!!pending||!data.settings.enabled" @click="train">训练并评估当前反馈</button><button :disabled="busy||!!pending" @click="reset('reset_model')">重置模型</button><button :disabled="busy||!!pending" @click="reset('clear_feedback')">清除反馈和行为记录</button><button :disabled="busy" @click="load">刷新学习状态</button></section><section v-if="data?.model"><h2>{{ data.model.accepted?'时间对照评估通过':'继续使用原排序' }}</h2><p>{{ data.model.reason }}</p><p class="note">训练时间 {{ new Date(data.model.trained_at).toLocaleString() }} · {{ data.model.model_version||data.model.algorithm }}</p><details v-if="data.model.metrics"><summary>查看时间对照结果</summary><p>训练 {{ data.model.metrics.train_count }} 条，测试 {{ data.model.metrics.test_count }} 条</p><p>训练截止 {{ data.model.metrics.train_end }}<br>测试开始 {{ data.model.metrics.test_start }}</p><p>原排序成对 AUC {{ data.model.metrics.original_pairwise_auc.toFixed(3) }}；个性化 {{ data.model.metrics.personalized_pairwise_auc.toFixed(3) }}</p><p class="note">这些是有限历史反馈上的离线指标，不是识别准确率或长期收益承诺。部署模型在对照通过后才使用全部已知反馈重新拟合。</p></details></section><section><h2>明确表达菜谱偏好</h2><p>每道菜只保留一份当前反馈；更新反馈会要求重新评估模型。</p><p v-if="!data?.settings.enabled">开启后可以提交反馈。浏览列表不会产生负反馈。</p><article v-for="r in recipes" :key="r.id" class="item"><h3>{{ r.recipe.dish_name }}</h3><p class="note">{{ r.recipe.tags?.join('、') }} · {{ r.recipe.method||'方法未标注' }}</p><p v-if="vote(r.id)">当前反馈：{{ vote(r.id).liked?'喜欢':'不喜欢' }}</p><button :aria-pressed="vote(r.id)?.liked===true" :disabled="busy||!!pending||!data?.settings.enabled" @click="feedback(r,true)">喜欢</button><button :aria-pressed="vote(r.id)?.liked===false" :disabled="busy||!!pending||!data?.settings.enabled" @click="feedback(r,false)">不喜欢</button></article></section></main></template>
<script setup>
import {ref,onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {ElMessageBox} from 'element-plus'
import {businessApi,apiError} from '../api/business'
import {usePendingCommand} from '../services/businessCommands'
import '../assets/business.css'
const router=useRouter(),data=ref(null),recipes=ref([])
const {busy,error,pending,send,retry}=usePendingCommand('learning',load)
async function load(){try{const [a,b]=await Promise.all([businessApi('/learning'),businessApi('/recipes/sources')]);data.value=a;recipes.value=b.items}catch(e){error.value=apiError(e)}}
const vote=id=>data.value?.feedback.find(f=>f.recipe_id===id),toggle=()=>send('/learning/settings','put',{enabled:!data.value.settings.enabled,expected_version:data.value.settings.version}),train=()=>send('/learning/train','post',{}),feedback=(r,liked)=>send('/learning/feedback/'+r.id,'put',{liked,expected_version:vote(r.id)?.version||0})
async function reset(action){try{await ElMessageBox.confirm(action==='clear_feedback'?'清除当前账号全部反馈、行为记录与模型？操作后回到原排序。':'删除当前模型并回到原排序？明确反馈会保留。','核对学习数据');await send('/learning/reset','post',{action})}catch(e){if(e!=='cancel'&&e!=='close')error.value=e.message}}
onMounted(load)
</script>
