<template><main class="business-page planner"><header><button @click="router.push('/home')" aria-label="返回首页">‹</button><h1>七日菜单</h1></header><p class="note">每餐安排主菜与主食，可选配菜。营养目标只针对勾选的餐次和全部用餐人数；保存计划不会扣库存或下单。</p><p v-if="error" role="alert" class="error">{{ error }}</p><section v-if="pending"><p>上次操作结果待核对。</p><button :disabled="busy" @click="retry">核对原操作</button></section>
<section><h2>餐次与约束</h2><form @submit.prevent="preview"><label>起始日期<input type="date" v-model="form.start_date" required></label><label>使用库存范围<select v-model="form.family_id"><option value="">个人库存</option><option v-for="f in families" :key="f.id" :value="f.id">家庭：{{ f.name }}</option></select></label><div class="week"><div v-for="day in 7" :key="day"><b>第 {{ day }} 天</b><label v-for="meal in mealNames" :key="meal.id"><input type="checkbox" v-model="selectedSlots" :value="`${day-1}:${meal.id}`">{{ meal.name }}</label></div></div><label><input type="checkbox" v-model="addSide">每个所选餐次增加配菜</label><label>用餐人数<input type="number" min="1" max="20" step="1" v-model.number="form.people" required></label><label>每人份量系数<input type="number" min="0.25" max="3" step="0.25" v-model.number="form.portion_factor" required></label><label>周预算（全部所选食材，元）<input type="number" min="0" max="100000" step="0.01" v-model="form.budget" placeholder="不限；使用此项需先填写价格"></label><label>每餐总操作时长上限（分钟）<input type="number" min="1" max="600" step="1" v-model.number="form.max_minutes" required></label><label>最高难度<select v-model.number="form.max_difficulty"><option :value="1">简单</option><option :value="2">中等</option><option :value="3">困难</option></select></label><label>同一道菜最多出现次数（主食除外）<input type="number" min="1" max="21" v-model.number="form.max_repeat" required></label><label>忌口食材<input v-model="avoid" placeholder="逗号分隔，例如：鸡蛋、花生"></label><label>饮食限制<select v-model="diet"><option value="">未设置</option><option>素食</option><option>纯素</option></select></label><label><input type="checkbox" v-model="form.inventory_priority">优先安排可评估的临期库存</label>
<details><summary>所选全部餐次的营养合计目标</summary><p class="note">原料估算值，涵盖当前人数；不是全天营养达标结论。</p><div v-for="n in nutrientLabels" :key="n.id"><label>{{ n.label }}下限<input type="number" min="0" step="any" v-model="bounds[n.id].min"></label><label>{{ n.label }}上限<input type="number" min="0" step="any" v-model="bounds[n.id].max"></label></div></details>
<details><summary>锁定指定菜</summary><p class="note">锁定不会突破忌口或其他硬约束。局部替换时可只更改目标位置，其余位置保持锁定。</p><div v-for="slot in slotObjects" :key="`${slot.day}:${slot.meal}`"><h3>第 {{ slot.day+1 }} 天 {{ mealLabel(slot.meal) }}</h3><label v-for="role in (addSide?['main','staple','side']:['main','staple'])" :key="role">{{ roleLabels[role] }}<select v-model="locks[`${slot.day}:${slot.meal}:${role}`]"><option value="">由求解器选择</option><option v-for="r in choices(slot.meal,role)" :key="r.id" :value="r.id">{{ r.name }}</option></select></label></div></details>
<label><input v-model="confirmed" type="checkbox" required>我已核对模板份量与食材映射，接受营养估算依据</label><p class="note">原 22 道菜按两人份工程模板，新增主食与早餐按一人份模板。通用大小、油品等可能与实物不同；估算仅用于规划，不换算库存。可在下方查看来源。</p><button class="primary" :disabled="busy||!!pending||!confirmed||!selectedSlots.length">计算菜单预览</button></form></section>
<section><details><summary>维护我的食材单价（元 / 所列单位）</summary><p class="note">缺价格保持空白，不视为零。无需预算时可以不填。只填写已核实的本地价格，最多四位小数。</p><label v-for="p in prices" :key="p.key">{{ p.name }} / {{ p.unit }}<input type="number" min="0" max="10000" step="0.0001" v-model="p.price"></label><button :disabled="busy||!!pending" @click="savePrices">保存价格</button></details><details><summary>营养数据与规划模板来源</summary><p class="note">USDA FoodData Central SR Legacy April 2018；数据下载与子集提取记录随项目提供。未匹配的食材保持缺失，带营养硬约束时排除对应菜谱。</p><details v-for="r in recipes" :key="r.id"><summary>{{ r.name }} · {{ r._planning.servings }} 人份</summary><p>{{ r._planning.servings_basis }}</p><p v-if="r.planning_nutrition.missing.length">缺少：{{ r.planning_nutrition.missing.join('、') }}</p><p v-for="e in r.planning_nutrition.evidence" :key="e.ingredient"><a :href="e.source_url" target="_blank" rel="noopener">{{ e.ingredient }}：FDC {{ e.fdc_id }}</a> · 每 {{ e.unit }} 估算 {{ e.grams_per_unit }} 克 · {{ e.description }}</p></details></details></section>
<section v-if="draft" aria-label="菜单预览"><h2>{{ solverLabels[draft.result.solver_status] }}</h2><p v-for="(issue,i) in draft.result.issues||[]" :key="i">{{ typeof issue==='string'?issue:issue.reason+'（'+issue.slot+' '+roleLabels[issue.role]+'）' }}</p><p>{{ draft.result.note }}</p><p v-if="draft.result.meals.length">菜单总估算成本：{{ money(draft.result.total_estimated_cost) }}；补购估算：{{ money(draft.result.shopping_estimated_cost) }}</p><p v-if="draft.result.nutrition">能量 {{ Math.round(draft.result.nutrition.kcal) }} kcal；蛋白质 {{ draft.result.nutrition.protein_g.toFixed(1) }} 克（所选餐次合计）</p><details v-if="draft.result.exclusions?.length"><summary>被排除的候选与缺失数据</summary><p v-for="(e,i) in draft.result.exclusions" :key="i">{{ recipeName(e.recipe_id) }}：{{ e.reason }} {{ e.missing?.join('、') }}</p></details><article v-for="m in draft.result.meals" :key="`${m.day}:${m.meal}`" class="item"><h3>第 {{ m.day+1 }} 天 {{ mealLabel(m.meal) }} · {{ m.minutes }} 分钟</h3><p v-for="d in m.dishes" :key="d.role">{{ roleLabels[d.role] }}：{{ d.name }} · 原菜谱 {{ d.factor }} 倍份量</p></article><label v-if="draft.result.meals.length">计划名称<input v-model="planName" maxlength="80"></label><button v-if="draft.result.meals.length" class="primary" :disabled="busy||!!pending" @click="save">确认保存此计划</button></section>
<section><h2>已保存计划</h2><button @click="loadMenus" :disabled="busy">刷新计划</button><article v-for="m in menus" :key="m.id" class="item"><h3>{{ m.name }}</h3><p>{{ m.config.start_date }} 起 · {{ m.config.people }} 人</p><button @click="check(m)" :disabled="busy">执行前重新核对</button><button @click="edit(m)" :disabled="busy">局部替换或重算</button></article></section>
<section v-if="checked" aria-label="菜单执行核对"><h2>{{ checked.menu.name }} · 执行前核对</h2><p>{{ checked.note }}</p><p v-if="checked.inventory_changed" class="error">库存已变化，采购需求须重算；烹饪前逐项核查。</p><p v-if="checked.price_changed">价格已更新，保存时估算可能过时。</p><p v-for="r in checked.inventory" :key="r.item.id">{{ r.item.name }} · {{ r.item.quantity }} {{ r.item.unit||'库存计数' }} · {{ r.freshness.freshness_label }}</p><article v-for="m in checked.menu.result.meals" :key="`${m.day}:${m.meal}`"><h3>第 {{ m.day+1 }} 天 {{ mealLabel(m.meal) }}</h3><button v-for="d in m.dishes" :key="d.role" :disabled="busy||!!pending" @click="clone(checked.menu,m,d)">复刻{{ d.name }}</button></article><button @click="router.push('/shopping')">前往共同采购</button></section>
</main></template>
<script setup>
import {ref,computed,onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {businessApi,apiError} from '../api/business'
import {usePendingCommand} from '../services/businessCommands'
import '../assets/business.css'
const router=useRouter(),mealNames=[{id:'breakfast',name:'早餐'},{id:'lunch',name:'午餐'},{id:'dinner',name:'晚餐'}],roleLabels={main:'主菜',staple:'主食',side:'配菜'},nutrientLabels=[{id:'kcal',label:'能量（kcal）'},{id:'protein_g',label:'蛋白质（克）'},{id:'fat_g',label:'脂肪（克）'},{id:'carb_g',label:'碳水（克）'}],solverLabels={OPTIMAL:'已找到最优解',FEASIBLE:'已找到可行解（尚未证明全部目标最优）',INFEASIBLE:'当前约束无解',TIMEOUT:'求解超时，尚无可行方案',NEEDS_DATA:'缺少验证约束所需的数据',MODEL_INVALID:'求解模型异常，请联系维护者'}
const tomorrow=new Date(Date.now()+86400000),dateText=`${tomorrow.getFullYear()}-${String(tomorrow.getMonth()+1).padStart(2,'0')}-${String(tomorrow.getDate()).padStart(2,'0')}`
const form=ref({start_date:dateText,family_id:'',people:1,portion_factor:1,budget:'',max_minutes:120,max_difficulty:2,max_repeat:3,inventory_priority:true}),selectedSlots=ref(Array.from({length:7},(_,day)=>[day+':lunch',day+':dinner']).flat()),addSide=ref(false),locks=ref({}),avoid=ref(''),diet=ref(''),confirmed=ref(false),bounds=ref(Object.fromEntries(nutrientLabels.map(n=>[n.id,{min:'',max:''}]))),recipes=ref([]),families=ref([]),prices=ref([]),priceVersion=ref(0),draft=ref(null),menus=ref([]),checked=ref(null),planName=ref('我的七日菜单')
const slotObjects=computed(()=>selectedSlots.value.map(s=>{const [day,meal]=s.split(':');return {day:Number(day),meal,side:addSide.value}}))
const {busy,error,pending,send,retry}=usePendingCommand('planning',async result=>{if(result.preview)draft.value=result.preview;if(result.prices)await loadCatalog();if(result.menu){await loadMenus();await check(result.menu)}if(result.copy)router.push('/recipes?copy='+result.copy.id)})
const choices=(meal,role)=>recipes.value.filter(r=>r._planning.meals.includes(meal)&&r._planning.roles.includes(role)),mealLabel=id=>mealNames.find(m=>m.id===id)?.name,recipeName=id=>recipes.value.find(r=>r.id===id)?.name||id,money=value=>value==null?'数据不足':value.toFixed(2)+' 元'
async function loadCatalog(){const data=await businessApi('/planning/catalog');recipes.value=data.recipes;priceVersion.value=data.prices.version;const inputs=new Map();for(const r of data.recipes)for(const i of r.ingredients){const key=i.name+'|'+i.unit;if(!inputs.has(key))inputs.set(key,{key,name:i.name,unit:i.unit,price:data.prices.items.find(p=>p.name===i.name&&p.unit===i.unit)?.price??''})}prices.value=[...inputs.values()]}
async function loadMenus(){try{menus.value=(await businessApi('/planning/menus')).items}catch(e){error.value=apiError(e)}}
function preview(){draft.value=null;const nutrition={};for(const [k,b] of Object.entries(bounds.value)){if(b.min!==''||b.max!=='')nutrition[k]={min:b.min===''?null:Number(b.min),max:b.max===''?null:Number(b.max)}}const chosen=[];for(const s of slotObjects.value)for(const role of (addSide.value?['main','staple','side']:['main','staple'])){const id=locks.value[`${s.day}:${s.meal}:${role}`];if(id)chosen.push({day:s.day,meal:s.meal,role,recipe_id:id})}send('/planning/preview','post',{...form.value,family_id:form.value.family_id||null,budget:form.value.budget===''?null:Number(form.value.budget),meals:slotObjects.value,locks:chosen,nutrition,avoid_ingredients:avoid.value.split(/[,，、]/).map(s=>s.trim()).filter(Boolean),dietary_restrictions:diet.value?[diet.value]:[],confirm_estimates:confirmed.value,utc_offset_hours:-new Date().getTimezoneOffset()/60})}
const savePrices=()=>send('/planning/prices','put',{expected_version:priceVersion.value,items:prices.value.filter(p=>p.price!=='').map(p=>({name:p.name,unit:p.unit,price:Number(p.price)}))}),save=()=>send('/planning/menus','post',{preview_id:draft.value.id,expected_version:draft.value.version,name:planName.value})
let checkRevision=0
async function check(menu){const revision=++checkRevision;checked.value=null;try{const result=await businessApi('/planning/menus/'+menu.id+'/check');if(revision===checkRevision)checked.value=result}catch(e){if(revision===checkRevision)error.value=apiError(e)}}
function edit(menu){const c=menu.config;form.value={start_date:c.start_date,family_id:c.family_id||'',people:c.people,portion_factor:c.portion_factor,budget:c.budget??'',max_minutes:c.max_minutes,max_difficulty:c.max_difficulty,max_repeat:c.max_repeat,inventory_priority:c.inventory_priority};selectedSlots.value=c.meals.map(s=>s.day+':'+s.meal);addSide.value=c.meals.some(s=>s.side);avoid.value=c.avoid_ingredients.join('、');diet.value=c.dietary_restrictions[0]||'';for(const n of nutrientLabels)bounds.value[n.id]={min:c.nutrition[n.id]?.min??'',max:c.nutrition[n.id]?.max??''};locks.value={};for(const s of menu.result.meals)for(const d of s.dishes)locks.value[`${s.day}:${s.meal}:${d.role}`]=d.recipe_id;confirmed.value=false;draft.value=null;error.value='已载入并锁定原计划，请展开“锁定指定菜”更改目标位置，再确认估算并重新计算。原计划保留。';window.scrollTo(0,0)}
const clone=(menu,m,d)=>send('/recipes/copies','post',{source_type:'menu',source_id:`${menu.id}|${m.day}|${m.meal}|${d.role}`,expected_source_version:String(menu.version)})
onMounted(async()=>{try{await loadCatalog();families.value=(await businessApi('/households')).items;await loadMenus()}catch(e){error.value=apiError(e)}})
</script>
<style scoped>.week{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.week>div{border:1px solid #dce5dd;border-radius:12px;padding:10px}.week label{display:flex;gap:8px;align-items:center}.week input{width:auto}.planner details{margin:12px 0}.planner article button{margin:5px}.planner a{overflow-wrap:anywhere}</style>
