<template>
 <main class="business-page"><header><button @click="router.push('/home')" aria-label="返回首页">‹</button><h1>共同采购清单</h1></header>
 <p class="note">认领后由认领成员标记购买。购买不会自动入库，收到食材后还需确认实际数量与储存信息。</p>
 <p v-if="error" role="alert" class="error">{{ error }}</p><section v-if="pending"><p>上次操作结果未确认，可用原凭证重试；不会重复执行。</p><button :disabled="busy" @click="retry">重试原操作</button></section>
 <section><label>选择家庭<select aria-label="选择家庭" v-model="selected" @change="load"><option value="">请选择</option><option v-for="f in families" :value="f.id" :key="f.id">{{ f.name }}</option></select></label><div class="actions"><button @click="load" :disabled="busy">刷新清单</button><button @click="router.push('/household')">管理家庭</button></div></section>
 <template v-if="selected">
  <section><h2>添加采购需求</h2><label>食材名称<input v-model="name" maxlength="80" /></label><div class="two"><label>需求数量（可未知）<input v-model="quantity" type="number" step="any" min="0.001" /></label><label>需求单位<input v-model="unit" placeholder="如：克、个；未知填待确认" maxlength="16" /></label></div><button class="primary" :disabled="busy||!!pending||!name.trim()||!unit.trim()" @click="send(root,'post',{name,quantity:quantity===''?null:Number(quantity),unit})">添加到共同清单</button><p class="note">仅同名、同单位的未认领需求合并。个、根、份与克数不自动换算。</p></section>
  <section><h2>从菜谱或菜单生成</h2><label>来源类型<select aria-label="来源类型" v-model="sourceType" @change="sourceId='' "><option value="recipe">标准菜谱</option><option value="menu">我的已保存菜单</option></select></label><label>选择来源<select aria-label="选择来源" v-model="sourceId"><option value="">请选择</option><option v-for="s in sourceType==='recipe'?sources.recipes:sources.menus" :key="s.id" :value="s.id">{{ s.name }}</option></select></label><label v-if="sourceType==='recipe'">原配方倍数<input v-model.number="multiplier" type="number" min="0.1" max="100" step="any" /></label><p class="note">菜谱份量不明时按原配方倍数计算，不推测人数。菜单使用已核对的补购需求。</p><button :disabled="busy||!!pending||!sourceId" @click="send(root+'/generate','post',{source_type:sourceType,source_id:sourceId,multiplier:sourceType==='recipe'?multiplier:1})">确认生成采购需求</button></section>
  <section><h2>待采购与待入库</h2><p v-if="!active.length" class="note">暂无待处理项目。</p><article v-for="item in active" :key="item.id" class="item"><b>{{ item.name }} · {{ item.quantity??'数量待确认' }} {{ item.unit }}</b><p class="note">{{ stateLabel(item) }}</p><div class="actions" v-if="item.state==='open'"><button v-if="!item.claimed_by" :disabled="busy||!!pending" @click="change(item,'claim')">我来采购</button><template v-if="!item.claimed_by||item.claimed_by===user"><button :disabled="busy||!!pending" @click="change(item,'bought')">标记已购买</button><button v-if="item.claimed_by" :disabled="busy||!!pending" @click="change(item,'release')">释放认领</button><button :disabled="busy||!!pending" @click="change(item,'cancel')">取消需求</button></template></div><button v-else-if="item.state==='bought'" :disabled="busy||!!pending" @click="prepareStock(item)">确认实际入库信息</button><details><summary>操作历史</summary><p class="note" v-for="(event,i) in item.history" :key="i">{{ eventLabels[event.type]||event.type }} · {{ new Date(event.at).toLocaleString() }}</p></details></article></section>
  <section v-if="stockItem" role="region" aria-label="采购入库确认"><h2>确认「{{ stockItem.name }}」实际入库</h2><label>实际数量<input v-model.number="stockQuantity" type="number" min="0.001" step="any" /></label><label>实际单位<select aria-label="实际单位" v-model="stockUnit"><option value="">请选择实际单位</option><option v-for="u in units" :key="u">{{ u }}</option></select></label><label>储存方式<select aria-label="储存方式" v-model="storage"><option :value="null">未知</option><option>常温</option><option>冷藏</option><option>冷冻</option></select></label><label>保质期（天，可未知）<input v-model="shelf" type="number" min="0.001" step="any" /></label><label>购买时间（可未知）<input v-model="purchase" type="datetime-local" /></label><label>到期时间（可未知）<input v-model="expiry" type="datetime-local" /></label><div class="actions"><button class="primary" :disabled="busy||!!pending||!stockUnit||!(stockQuantity>0)" @click="stockIn">确认入家庭冰箱</button><button @click="stockItem=null">取消</button></div></section>
  <section><h2>采购历史</h2><p v-if="!history.length" class="note">暂无已结束项目。</p><article v-for="item in history" :key="item.id" class="item"><b>{{ item.name }} · {{ stateLabel(item) }}</b><p v-for="(event,i) in item.history" :key="i" class="note">{{ eventLabels[event.type]||event.type }} · {{ new Date(event.at).toLocaleString() }}<template v-if="event.type==='stocked'"> · 实际 {{ event.quantity }} {{ event.unit }}</template></p></article></section>
 </template></main>
</template>
<script setup>
import {ref,computed,onMounted} from 'vue'
import {useRouter} from 'vue-router'
import {businessApi,apiError} from '../api/business'
import {readUserId} from '../services/recognitionDraft'
import {usePendingCommand} from '../services/businessCommands'
import '../assets/business.css'
const router=useRouter(),user=readUserId(),families=ref([]),selected=ref(''),items=ref([]),sources=ref({recipes:[],menus:[]}),name=ref(''),quantity=ref(''),unit=ref(''),sourceType=ref('recipe'),sourceId=ref(''),multiplier=ref(1)
const stockItem=ref(null),stockQuantity=ref(1),stockUnit=ref('库存计数'),storage=ref(null),shelf=ref(''),purchase=ref(''),expiry=ref('')
const units=['库存计数','克','千克','毫升','升','个','根','份','瓣','片','袋','包'],eventLabels={added:'添加需求',claim:'认领',release:'释放认领',bought:'标记购买',cancel:'取消需求',stocked:'确认入库'}
const {pending,busy,error,send,retry}=usePendingCommand('shopping',async()=>{stockItem.value=null;await load()})
const root=computed(()=>`/households/${selected.value}/shopping`),active=computed(()=>items.value.filter(i=>['open','bought'].includes(i.state))),history=computed(()=>items.value.filter(i=>!['open','bought'].includes(i.state)))
function stateLabel(item){return item.state==='bought'?'已购买，等待确认实际入库':item.state==='stocked'?'已入库':item.state==='cancelled'?'已取消':item.claimed_by?(item.claimed_by===user?'我已认领':'其他成员已认领'):'未认领'}
async function load(){items.value=[];sources.value={recipes:[],menus:[]};stockItem.value=null;if(!selected.value)return;try{const [list,catalog]=await Promise.all([businessApi(root.value),businessApi(root.value+'/sources')]);items.value=list.items;sources.value=catalog}catch(e){error.value=apiError(e)}}
const change=(item,action)=>send(root.value+'/'+item.id+'/state','post',{expected_version:item.version,action})
function prepareStock(item){stockItem.value=item;stockQuantity.value=item.quantity??'';stockUnit.value=units.includes(item.unit)?item.unit:'';storage.value=null;shelf.value='';purchase.value='';expiry.value=''}
async function stockIn(){try{await send(root.value+'/'+stockItem.value.id+'/stock-in','post',{expected_version:stockItem.value.version,name:stockItem.value.name,quantity:stockQuantity.value,unit:stockUnit.value,storage_type:storage.value,shelf_life:shelf.value===''?null:Number(shelf.value),purchase_time:purchase.value?new Date(purchase.value).toISOString():null,expiry_date:expiry.value?new Date(expiry.value).toISOString():null})}catch(e){error.value=apiError(e)}}
onMounted(async()=>{try{families.value=(await businessApi('/households')).items;selected.value=families.value[0]?.id||'';await load()}catch(e){error.value=apiError(e)}})
</script>
